version: '3'

services:
  app:
    build: .
    image: analytics-service
    container_name: analytics
    ports:
      - "8083:8083"
    networks:
        - microservice_analytics
    depends_on:
        - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/analytics_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
  db:
    image: postgres
    container_name: postgres-analytics
    ports:
      - "5432:5432"
    networks:
      - microservice_analytics
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: analytics_db
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-analytics
    ports:
      - "5050:80"
    networks:
      - microservice_analytics
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin_password


volumes:
  db_data:

networks:
  microservice_analytics:
    driver: bridge