server:
  port: ${SERVER_PORT:8083}

graphql:
  date-scalar:
    format: yyyy-MM-dd
    name: Date
    enabled: true
  extended-scalars: Date
  exception-handlers-enabled: true
  extended-scalars-enabled: true
  extended-scalars-date-format: yyyy-MM-dd
  servlet:
    mapping: /graphql
spring:
  datasource:
    host: ${DB_HOST:localhost}
    port: ${DB_PORT:5432}
    name: ${POSTGRES_DB:analytics_db}
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.name}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:password}
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    show-sql: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${DDL:update}